Repository hashicorp/consul-dataplane, pull requests merged in 2023-07, with the labels that each got.

#140 fix(connect): set initial_fetch_time to wait indefinitely
  .changelog/140.txt
  internal/bootstrap/bootstrap_tpl.go
  pkg/consuldp/testdata/TestBootstrapConfig/access-logs.golden
  pkg/consuldp/testdata/TestBootstrapConfig/basic.golden
  pkg/consuldp/testdata/TestBootstrapConfig/central-telemetry-config.golden
  pkg/consuldp/testdata/TestBootstrapConfig/custom-prometheus-scrape-path.golden
  pkg/consuldp/testdata/TestBootstrapConfig/hcp-metrics.golden
  pkg/consuldp/testdata/TestBootstrapConfig/ready-listener.golden
  pkg/consuldp/testdata/TestBootstrapConfig/unix-socket-xds-server.golden
Labels: backport/1.0, backport/1.1, backport/1.2

#202 bump proto public to released 0.4.0
  go.mod
  go.sum
Labels: pr/no-changelog, backport/1.2

#201 Add 1.2.0 changelog
  CHANGELOG.md
Labels: pr/no-changelog, backport/1.2

#203 Fix FIPS version delimiter
  .github/workflows/build.yml
  pkg/version/version.go
Labels: pr/no-changelog, backport/1.2

#215 Update new 1.2.x version
  pkg/version/version.go
Labels: pr/no-changelog

#217 Correct FIPS Redhat registry
  .github/workflows/build.yml
Labels: pr/no-changelog, backport/1.2

#219 [NET-4865] security: Upgrade Go and net/http CVE-2023-29406
  .changelog/219.txt
  .github/workflows/build.yml
  .github/workflows/consul-dataplane-checks.yaml
  .go-version
  go.mod
  go.sum
  integration-tests/go.mod
  integration-tests/go.sum
Labels: backport/1.0, backport/1.1, backport/1.2

#223 [NET-4865] Bump server-connection-manager to v0.1.3
  go.mod
  go.sum
Labels: pr/no-changelog, backport/1.0, backport/1.1, backport/1.2
