Repository hashicorp/consul-dataplane, pull requests merged in 2023-05, with the labels that each got.

#94 security: update Go version to 1.20.4
  .changelog/94.txt
  .go-version
Labels: backport/1.0, backport/1.1

#106 Support HOST_IP expansion
  .changelog/106.txt
  pkg/consuldp/metrics.go
  pkg/consuldp/metrics_test.go
Labels: backport/1.0, backport/1.1

#104 fix: set initial_fetch_timeout to wait for initial xDS…
  .changelog/104.txt
  internal/bootstrap/bootstrap_tpl.go
  pkg/consuldp/testdata/TestBootstrapConfig/access-logs.golden
  pkg/consuldp/testdata/TestBootstrapConfig/basic.golden
  pkg/consuldp/testdata/TestBootstrapConfig/central-telemetry-config.golden
  pkg/consuldp/testdata/TestBootstrapConfig/custom-prometheus-scrape-path.golden
  pkg/consuldp/testdata/TestBootstrapConfig/hcp-metrics.golden
  pkg/consuldp/testdata/TestBootstrapConfig/ready-listener.golden
  pkg/consuldp/testdata/TestBootstrapConfig/unix-socket-xds-server.golden
Labels: backport/1.0, backport/1.1

#120 Bump up gh-action-jira modules
  .github/workflows/jira-issues.yaml
  .github/workflows/jira-pr.yaml
Labels: pr/no-changelog

#122 Update bootstrap configuration
  .changelog/122.txt
  internal/bootstrap/bootstrap_config.go
  internal/bootstrap/bootstrap_config_test.go
  internal/bootstrap/bootstrap_tpl.go
  pkg/consuldp/bootstrap_test.go
  pkg/consuldp/testdata/TestBootstrapConfig/hcp-metrics.golden
Labels: backport/1.0, backport/1.1

#125 build(deps): update UBI base to 9.2
  .changelog/125.txt
  Dockerfile
Labels: backport/1.0, backport/1.1

#128 Stage release 1.1.1
  CHANGELOG.md
Labels: pr/no-changelog

#129 docs: update changelog for 1.1.1
  CHANGELOG.md
Labels: pr/no-changelog

#121 Add FIPS builds
  .github/workflows/build.yml
  pkg/version/fips_build.go
  pkg/version/non_fips_build.go
  pkg/version/version.go
Labels: pr/no-changelog

#131 Revert #104 and remove fetch timeout for envoy
  .changelog/131.txt
  internal/bootstrap/bootstrap_tpl.go
  pkg/consuldp/testdata/TestBootstrapConfig/access-logs.golden
  pkg/consuldp/testdata/TestBootstrapConfig/basic.golden
  pkg/consuldp/testdata/TestBootstrapConfig/central-telemetry-config.golden
  pkg/consuldp/testdata/TestBootstrapConfig/custom-prometheus-scrape-path.golden
  pkg/consuldp/testdata/TestBootstrapConfig/hcp-metrics.golden
  pkg/consuldp/testdata/TestBootstrapConfig/ready-listener.golden
  pkg/consuldp/testdata/TestBootstrapConfig/unix-socket-xds-server.golden
Labels: backport/1.1
