Repository hashicorp/consul-dataplane, pull requests merged in 2023-06, with the labels that each got.

#136 Stage release v1.1.2
  CHANGELOG.md
  pkg/version/version.go
Labels: pr/no-changelog

#137 Stage release v1.0.3
  CHANGELOG.md
  pkg/version/version.go
Labels: pr/no-changelog

#138 Changelog for initial fetch timeout revert release
  CHANGELOG.md
Labels: pr/no-changelog

#142 bump to Envoy 1.26.2
  .changelog/142.txt
  Dockerfile
Labels: backport/1.2

#141 chore(ci): update integration tests and build for 1.3.x
  .github/workflows/build.yml
  pkg/version/version.go
Labels: pr/no-changelog

#144 Stage release v1.2.0-rc1
  CHANGELOG.md
  go.mod
  go.sum
  pkg/version/version.go
Labels: pr/no-changelog

#145 build: updates from 1.2.0-rc1 release
  CHANGELOG.md
  go.mod
  go.sum
Labels: pr/no-changelog

#148 [chore]: Pin github action workflows
  .github/workflows/bot-auto-approve.yaml
  .github/workflows/build.yml
  .github/workflows/consul-dataplane-checks.yaml
  .github/workflows/jira-issues.yaml
  .github/workflows/jira-pr.yaml
Labels: pr/no-changelog

#152 Revert Proxy Lifecycle PRs
  .changelog/100.txt
  .changelog/115.txt
  .changelog/130.txt
  .github/workflows/consul-dataplane-checks.yaml
  Makefile
  cmd/consul-dataplane/main.go
  integration-tests/helpers/dataplane.go
  integration-tests/helpers/suite.go
  integration-tests/main_test.go
  pkg/consuldp/config.go
  pkg/consuldp/consul_dataplane.go
  pkg/consuldp/lifecycle.go
  pkg/consuldp/lifecycle_test.go
  pkg/consuldp/metrics.go
  pkg/consuldp/metrics_test.go
  pkg/envoy/proxy.go
  pkg/envoy/proxy_test.go
Labels: pr/no-changelog

#153 Updating go-discover to the latest version
  Dockerfile
Labels: pr/no-changelog, backport/1.0, backport/1.1, backport/1.2

#159 Add changelog to release branches
  .changelog/153.txt
Labels: pr/no-changelog, backport/1.0, backport/1.1, backport/1.2

#165 Fix broken proxy tests in release/1.2.x
  pkg/envoy/proxy_test.go
Labels: pr/no-changelog

#154 Add CRT updates and FIPS envoy image
  .github/workflows/build.yml
  Dockerfile
Labels: pr/no-changelog, backport/1.2

#168 add fips staging docker repo tags
  .github/workflows/build.yml
Labels: pr/no-changelog, backport/1.2

#170 Separate FIPS and non-FIPS build steps
  .github/workflows/build.yml
Labels: pr/no-changelog, backport/1.2

#175 Do not throw error on exit
  .changelog/175.txt
  pkg/consuldp/consul_dataplane.go
  pkg/envoy/proxy.go
Labels: backport/1.0, backport/1.1

#184 Add emit_tags_as_labels setting to envoy metrics service cfg
  .changelog/184.txt
  internal/bootstrap/bootstrap_config.go
  internal/bootstrap/bootstrap_config_test.go
  pkg/consuldp/testdata/TestBootstrapConfig/hcp-metrics.golden
Labels: backport/1.0, backport/1.1, backport/1.2
