Repository hashicorp/consul-dataplane, pull requests merged in 2023-08, with the labels that each got.

#227 [NET-5146] security: Upgrade Go and `x/net`
  .changelog/227.txt
  .go-version
  go.mod
  go.sum
  integration-tests/go.mod
  integration-tests/go.sum
Labels: backport/1.0, backport/1.1, backport/1.2

#216 Differentiate linux package names
  .github/workflows/build.yml
Labels: pr/no-changelog, backport/1.2

#235 [NET-4904] security: update Envoy to 1.26.4
  .changelog/235.txt
  Dockerfile
Labels: backport/1.2

#243 [NET-4904] security: Update Envoy FIPS to 1.26.4
  Dockerfile
Labels: pr/no-changelog, backport/1.2

#239 net 2898, graceful_startup
  .changelog/239.txt
  cmd/consul-dataplane/config.go
  cmd/consul-dataplane/config_test.go
  cmd/consul-dataplane/main.go
  pkg/consuldp/config.go
  pkg/consuldp/lifecycle.go
  pkg/consuldp/lifecycle_test.go
  pkg/envoy/proxy.go
Labels: backport/1.0, backport/1.1, backport/1.2

#238 NET-5186 Allow dataplane container to bind to privileged ports
  .changelog/238.txt
  Dockerfile
Labels: backport/1.0, backport/1.1, backport/1.2
