Repository hashicorp/consul-dataplane, pull requests merged in 2023-10, with the labels that each got.

#272 updated proto-public
  go.mod
  go.sum
  pkg/consuldp/bootstrap.go
  pkg/consuldp/bootstrap_test.go
Labels: pr/no-changelog

#273 updated proto-public (#272)
  go.mod
  go.sum
  pkg/consuldp/bootstrap.go
  pkg/consuldp/bootstrap_test.go
Labels: pr/no-changelog

#274 Update JIRA sync workflow to use 'gh' instead of 'hub'
  .github/workflows/jira-pr.yaml
Labels: pr/no-changelog

#276 Update backport assistant to use merge commits
  .github/workflows/backport-assistant.yml
Labels: pr/no-changelog, backport/1.1, backport/1.2, backport/1.0

#279 manual backport of update backport assistant to use merge commits to 1.0.x
  .github/workflows/backport-assistant.yml
Labels: pr/no-changelog

#280 manual backport of update backport assistant to use merge commits to 1.1.x
  .github/workflows/backport-assistant.yml
Labels: pr/no-changelog

#281 Get correct docker tags for everything
  .github/workflows/build.yml
Labels: pr/no-changelog, backport/1.1, backport/1.2, backport/1.0

#283 revert backport assistant change
  .github/workflows/backport-assistant.yml
Labels: pr/no-changelog

#299 [NET-5944] security: Upgrade Go and x/net
  .changelog/299.txt
  .go-version
  Dockerfile
  go.mod
  go.sum
  integration-tests/go.mod
  integration-tests/go.sum
Labels: backport/1.1, backport/1.2, backport/1.0

#304 bump version.go
  pkg/version/version.go
Labels: pr/no-changelog

#305 remove dev tag to eliminate race
  pkg/version/version.go
Labels: pr/no-changelog

#306 build(docker): always publish full and minor version tags for dev images
  .github/workflows/build.yml
Labels: pr/no-changelog, backport/1.1, backport/1.2, backport/1.0, backport/1.3

#309 build(docker): always publish full and minor version tags for dev images
  .github/workflows/build.yml
Labels: pr/no-changelog

#319 release/1.3.x - Update FIPS Envoy version
  Dockerfile
Labels: pr/no-changelog

#318 release/1.3.0 - Update FIPS Envoy version
  Dockerfile
Labels: pr/no-changelog

#317 Update FIPS Envoy
  Dockerfile
Labels: pr/no-changelog

#320 release/1.2.x - Update FIPS Envoy version
  Dockerfile
Labels: pr/no-changelog
