Repository hashicorp/consul-dataplane, pull requests merged in 2023-11, with the labels that each got.

#339 Release 1.3.0
  .changelog/133.txt
  CHANGELOG.md
  go.mod
  go.sum
Labels: backport/1.3

#342 add 1.3.0 changelog entries
  CHANGELOG.md
Labels: pr/no-changelog, backport/1.3

#341 chore: skaffold build experiment
  Dockerfile.dev
  Makefile
Labels: pr/no-changelog

#344 uniform makefile experience
  .github/workflows/consul-dataplane-checks.yaml
  Makefile
Labels: pr/no-changelog, backport/1.1, backport/1.2, backport/1.0, backport/1.3
