Repository hashicorp/consul-dataplane, pull requests merged in 2023-02, with the labels that each got.

#72 chore(ci): update dev builds to v1.2
  .github/workflows/build.yml
  pkg/version/version.go
Labels: pr/no-changelog

#73 chore(ci): add backport-assistant
  .github/workflows/backport-assistant.yml
  .github/workflows/consul-dataplane-checks.yaml
Labels: pr/no-changelog

#74 Update consul-server-connection-manager to 0.1.2
  .changelog/74.txt
  go.mod
  go.sum
Labels: backport/1.0, backport/1.1

#81 Update golang.org/x/net from v0.4.0
  .changelog/81.txt
  go.mod
  go.sum
Labels: backport/1.0, backport/1.1

#85 chore: update proto-public to v0.3.0
  go.mod
  go.sum
Labels: pr/no-changelog, backport/1.1

#88 Stage release v1.1.0
  CHANGELOG.md
Labels: pr/no-changelog
