Repository hashicorp/consul-dataplane, pull requests merged in 2024-09, with the labels that each got.

#608 Upgrade Go to 1.22.7
  .changelog/608.txt
  .go-version
Labels: backport/1.1, backport/1.3, backport/1.4, backport/1.5

#619 ci: update the security-scanner gha token
  .github/workflows/security-scan.yml
Labels: pr/no-changelog, backport/1.1, backport/1.3, backport/1.4, backport/1.5

#624 Bump envoy version
  .changelog/624.txt
  Dockerfile
Labels: backport/1.6

#627 1.6.0-rc changelog
  CHANGELOG.md
Labels: pr/no-changelog, backport/1.6

#637 [NET-11150] ci: fix conditional skip and add safeguard
  .github/scripts/check_skip_ci.sh
  .github/workflows/build.yml
  .github/workflows/consul-dataplane-checks.yaml
  .github/workflows/reusable-conditional-skip.yml
  .github/workflows/security-scan.yml
Labels: pr/no-changelog, backport/1.1, backport/1.3, backport/1.4, backport/1.5, backport/1.6

#643 Backport of [NET-11150] ci: fix conditional skip and add safeguard into release/1.6.x
  .github/scripts/check_skip_ci.sh
  .github/workflows/build.yml
  .github/workflows/consul-dataplane-checks.yaml
  .github/workflows/reusable-conditional-skip.yml
  .github/workflows/security-scan.yml
Labels: pr/no-changelog

#645 Init 1.6.0 branch
  pkg/version/version.go
Labels: pr/no-changelog
