Repository hashicorp/consul-dataplane, pull requests merged in 2024-05, with the labels that each got.

#484 chore: remove workstream from JIRA sync
  .github/workflows/jira-issues.yaml
  .github/workflows/jira-pr.yaml
Labels: pr/no-changelog

#485 chore: fix JIRA workflow
  .github/workflows/jira-issues.yaml
  .github/workflows/jira-pr.yaml
Labels: pr/no-changelog

#487 security: Upgrade Go to 1.21.10
  .changelog/487.txt
  .go-version
Labels: backport/1.1, backport/1.2, backport/1.3, backport/1.4

#489 Backport of Node16 to Node20 into release/1.2.x
  .github/workflows/bot-auto-approve.yaml
  .github/workflows/build.yml
  .github/workflows/changelog-checker.yml
  .github/workflows/consul-dataplane-checks.yaml
  .github/workflows/reusable-get-go-version.yml
  .github/workflows/security-scan.yml
Labels: pr/no-changelog

#501 upgrade go to 1.22.3
  .changelog/501.txt
  .go-version
Labels: backport/1.1, backport/1.2, backport/1.3, backport/1.4

#506 bump version
  pkg/version/version.go
Labels: pr/no-changelog

#508 Prepare 1.4.2
  go.mod
  go.sum
  pkg/version/version.go
Labels: pr/no-changelog

#510 Prepare release 1.4.2
  CHANGELOG.md
  go.mod
  go.sum
  pkg/version/version.go
Labels: pr/no-changelog

#511 Stage release 1.3.5
  CHANGELOG.md
  pkg/version/version.go
Labels: pr/no-changelog

#512 Stage release 1.3.5
  CHANGELOG.md
  pkg/version/version.go
Labels: pr/no-changelog

#513 Stage release 1.2.8
  CHANGELOG.md
  pkg/version/version.go
Labels: pr/no-changelog

#514 Stage release 1.2.8
  CHANGELOG.md
  pkg/version/version.go
Labels: pr/no-changelog

#516 Stage release 1.1.11
  CHANGELOG.md
  pkg/version/version.go
Labels: pr/no-changelog

#515 Stage release 1.1.11
  CHANGELOG.md
  pkg/version/version.go
Labels: pr/no-changelog

#517 put version back
  pkg/version/version.go
Labels: pr/no-changelog

#519 update version
  pkg/version/version.go
Labels: pr/no-changelog

#520 update version
  pkg/version/version.go
Labels: pr/no-changelog

#522 build: prepare for 1.6.0 dev
  .github/workflows/build.yml
  go.mod
  go.sum
  pkg/version/version.go
Labels: pr/no-changelog

#525 [NET-9445] chore: update api dep for int tests
  integration-tests/go.mod
  integration-tests/go.sum
Labels: pr/no-changelog, backport/1.5

#526 Backport of [NET-9445] chore: update api dep for int tests into release/1.5.x
  integration-tests/go.mod
  integration-tests/go.sum
Labels: pr/no-changelog

#527 [NET-9445] build: prepare for 1.5.1 dev
  pkg/version/version.go
Labels: pr/no-changelog
