Repository hashicorp/consul-dataplane, pull requests merged in 2024-02, with the labels that each got.

#407 bumped version
  pkg/version/version.go
Labels: pr/no-changelog

#408 Prepare rc
  pkg/version/version.go
Labels: pr/no-changelog

#406 Bump consul/proto-public and create mocks
  Makefile
  go.mod
  go.sum
  internal/mocks/pbdnsmock/dns_service_client.go
  internal/mocks/pbdnsmock/dns_service_server.go
  internal/mocks/pbdnsmock/is_cloning_dns_service_client.go
  internal/mocks/pbdnsmock/unsafe_dns_service_server.go
  internal/mocks/pbresourcemock/is_cloning_resource_service_client.go
  internal/mocks/pbresourcemock/resource_service__watch_list_client.go
  internal/mocks/pbresourcemock/resource_service__watch_list_server.go
  internal/mocks/pbresourcemock/resource_service_client.go
  internal/mocks/pbresourcemock/resource_service_server.go
  internal/mocks/pbresourcemock/server_stream.go
  internal/mocks/pbresourcemock/unsafe_resource_service_server.go
  pkg/dns/dns_test.go
Labels: pr/no-changelog, backport/1.4

#409 Backport of Bump consul/proto-public and create mocks into release/1.4.x
  Makefile
  go.mod
  go.sum
  internal/mocks/pbdnsmock/dns_service_client.go
  internal/mocks/pbdnsmock/dns_service_server.go
  internal/mocks/pbdnsmock/is_cloning_dns_service_client.go
  internal/mocks/pbdnsmock/unsafe_dns_service_server.go
  internal/mocks/pbresourcemock/is_cloning_resource_service_client.go
  internal/mocks/pbresourcemock/resource_service__watch_list_client.go
  internal/mocks/pbresourcemock/resource_service__watch_list_server.go
  internal/mocks/pbresourcemock/resource_service_client.go
  internal/mocks/pbresourcemock/resource_service_server.go
  internal/mocks/pbresourcemock/server_stream.go
  internal/mocks/pbresourcemock/unsafe_resource_service_server.go
  pkg/dns/dns_test.go
Labels: pr/no-changelog

#410 Stage 1.4.0-rc1
  CHANGELOG.md
  go.mod
  go.sum
  pkg/dns/.mockery.yaml
  pkg/dns/dns_test.go
  pkg/dns/mocks/mock_DNSServiceClient.go
  pkg/dns/mocks/mock_DNSServiceServer.go
  pkg/dns/mocks/mock_UnsafeDNSServiceServer.go
Labels: pr/no-changelog

#411 use go 1.21.7
  .changelog/411.txt
  .go-version
Labels: backport/1.2, backport/1.3, backport/1.4

#416 [NET-7948] security: update Envoy to 1.28.1
  .changelog/416.txt
  Dockerfile
Labels: backport/1.4

#370 Add exporting of Envoy metrics to HCP for linked clusters
  .changelog/370.txt
  go.mod
  go.sum
  pkg/consuldp/consul_dataplane.go
  pkg/consuldp/metrics_test.go
  pkg/hcp/telemetry/doc.go
  pkg/hcp/telemetry/exporter.go
  pkg/hcp/telemetry/exporter_test.go
  pkg/hcp/telemetry/otlphttp/client.go
  pkg/hcp/telemetry/otlphttp/client_test.go
  pkg/hcp/telemetry/otlphttp/middleware.go
  pkg/hcp/telemetry/scraper.go
  pkg/hcp/telemetry/scraper_test.go
  pkg/hcp/telemetry/state.go
  pkg/hcp/telemetry/state_test.go
  pkg/hcp/telemetry/testdata/envoy_admin_stats_prometheus
  pkg/hcp/telemetry/testdata/envoy_stats_otlp_example.json
Labels: backport/1.4

#425 [NET-7991] security: update Envoy to 1.26.7 (FIPS)
  Dockerfile
Labels: pr/no-changelog

#423 [NET-7991] security: update Envoy to 1.28.1 (FIPS)
  Dockerfile
Labels: pr/no-changelog, backport/1.4

#424 [NET-7991] security: update Envoy to 1.27.3 (FIPS)
  Dockerfile
Labels: pr/no-changelog

#432 Fix incorrect year
  CHANGELOG.md
Labels: pr/no-changelog

#431 Fix incorrect year
  CHANGELOG.md
Labels: pr/no-changelog

#430 Stage release 1.3.3
  CHANGELOG.md
  pkg/version/version.go
Labels: pr/no-changelog

#434 Update Dockerfile - bump UBI image to 9.3 for FIPS
  .changelog/434.txt
  Dockerfile
Labels: backport/1.2, backport/1.3, backport/1.4

#438 Stage release v1.4.0
  CHANGELOG.md
  pkg/version/version.go
Labels: pr/no-changelog

#433 [NET-2420] security: add security scans on protected branches
  .github/workflows/security-scan.yml
  .release/security-scan.hcl
  scan.hcl
Labels: pr/no-changelog, backport/1.1, backport/1.2, backport/1.3, backport/1.4

#456 Backport of Revert: Add exporting of Envoy metrics to HCP for linked …
  .changelog/370.txt
  go.mod
  go.sum
  pkg/consuldp/consul_dataplane.go
  pkg/consuldp/metrics_test.go
  pkg/hcp/telemetry/doc.go
  pkg/hcp/telemetry/exporter.go
  pkg/hcp/telemetry/exporter_test.go
  pkg/hcp/telemetry/otlphttp/client.go
  pkg/hcp/telemetry/otlphttp/client_test.go
  pkg/hcp/telemetry/otlphttp/middleware.go
  pkg/hcp/telemetry/scraper.go
  pkg/hcp/telemetry/scraper_test.go
  pkg/hcp/telemetry/state.go
  pkg/hcp/telemetry/state_test.go
  pkg/hcp/telemetry/testdata/envoy_admin_stats_prometheus
  pkg/hcp/telemetry/testdata/envoy_stats_otlp_example.json
Labels: pr/no-changelog

#458 1.4.0 updates: bump proto-public, add missing changelog entries, cherry-pick test fixes
  CHANGELOG.md
  go.mod
  go.sum
  pkg/dns/.mockery.yaml
  pkg/dns/dns_test.go
  pkg/dns/mocks/mock_DNSServiceClient.go
  pkg/dns/mocks/mock_DNSServiceServer.go
  pkg/dns/mocks/mock_UnsafeDNSServiceServer.go
Labels: pr/no-changelog, backport/1.4
