Repository hashicorp/consul-dataplane, pull requests merged in 2024-06, with the labels that each got.

#528 ci: update security-scanner token
  .github/workflows/security-scan.yml
Labels: pr/no-changelog

#529 update go version to 1.22.4
  .changelog/529.txt
  .go-version
Labels: backport/1.3, backport/1.4, backport/1.5

#534 docs: fix missing changelog entries up to 1.4.2
  CHANGELOG.md
Labels: pr/no-changelog

#533 Update envoy version in dockerfile
  .changelog/533.txt
  Dockerfile
Labels: backport/1.5

#545 [NET-10001] test: replace deprecated google/pause container
  integration-tests/helpers/pod.go
Labels: pr/no-changelog, backport/1.1, backport/1.3, backport/1.4, backport/1.5

#550 Backport of [NET-10001] test: replace deprecated google/pause container into release/1.5.0
  integration-tests/helpers/pod.go
Labels: pr/no-changelog

#551 ci: add integration-tests summary job for required check
  .github/workflows/build.yml
Labels: pr/no-changelog, backport/1.1, backport/1.3, backport/1.4, backport/1.5

#557 docs: update CHANGELOG.md for 1.5.0
  CHANGELOG.md
Labels: pr/no-changelog, backport/1.5

#558 chore: update proto-public to 0.6.1
  go.mod
  go.sum
  integration-tests/go.mod
  integration-tests/go.sum
Labels: pr/no-changelog, backport/1.5

#560 ci: add conditional skip for docs changes
  .github/scripts/check_skip_ci.sh
  .github/workflows/build.yml
  .github/workflows/consul-dataplane-checks.yaml
  .github/workflows/reusable-conditional-skip.yml
  .github/workflows/security-scan.yml
Labels: pr/no-changelog, backport/1.1, backport/1.3, backport/1.4, backport/1.5

#566 remove macos runners from buildworkflow
  .github/workflows/build.yml
Labels: pr/no-changelog, backport/1.1, backport/1.3, backport/1.4, backport/1.5
