Repository hashicorp/consul-dataplane, pull requests merged in 2025-06, with the labels that each got.

#753 update: version to next release 1.7.2 in version.go
  pkg/version/version.go
Labels: pr/no-changelog

#760 updated primary codeowners
  .github/CODEOWNERS
Labels: pr/no-changelog, backport/all

#764 upgraded golang.org/x/net package to address CVEs
  .changelog/764.txt
  go.mod
  go.sum
Labels: backport/all

#766 Backport of changes from main to release/1.6.x
  .changelog/759.txt
  .changelog/764.txt
  .github/CODEOWNERS
  .github/workflows/build.yml
  .go-version
  Dockerfile
  go.mod
  go.sum
  integration-tests/go.mod
  integration-tests/go.sum
Labels: pr/no-changelog

#767 Backport of changes from main to release/1.5.x
  .changelog/759.txt
  .changelog/764.txt
  .github/CODEOWNERS
  .github/workflows/build.yml
  .go-version
  Dockerfile
  go.mod
  go.sum
  integration-tests/go.mod
  integration-tests/go.sum
Labels: pr/no-changelog
