Repository hashicorp/consul-dataplane, pull requests merged in 2025-03, with the labels that each got.

#687 Triggering graceful startup if gracefulStartupSeconds is grtr than 0
  .changelog/687.txt
  pkg/consuldp/consul_dataplane.go
  pkg/consuldp/lifecycle.go
  pkg/envoy/proxy.go
Labels: backport/1.4, backport/1.5, backport/1.6

#692 fixed envoy fips version
  Dockerfile
Labels: pr/no-changelog

#691 fixed envoy fips version
  Dockerfile
Labels: pr/no-changelog

#697 Prepping release 1.7.0 rc1
  CHANGELOG.md
  pkg/version/version.go
Labels: pr/no-changelog

#698 upgraded x/net dependency to fix vulnerability GO-2024-3333
  .changelog/698.txt
  go.mod
  go.sum
Labels: backport/1.7

#700 Backport of upgraded x/net dependency to fix vulnerability GO-2024-3333 into release/1.7.x
  .changelog/698.txt
  go.mod
  go.sum
Labels: pr/no-changelog

#702 update Go modules to fix CVEs
  .changelog/702.txt
  go.mod
  go.sum
Labels: backport/all

#717 Post release 1.5.6
  CHANGELOG.md
  pkg/version/version.go
Labels: pr/no-changelog
